/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * devTestStrBox.java
 *
 * Created on Jul 30, 2009, 2:07:18 AM
 */

package Falcon;

import org.jdesktop.application.Action;

/**
 *
 * @author Joe
 */
public class devTestStrBox extends javax.swing.JDialog {

    /** Creates new form devTestStrBox */
    public devTestStrBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testStrDescLabel = new javax.swing.JLabel();
        testStrText = new javax.swing.JTextField();
        testStrLabel = new javax.swing.JLabel();
        sendTestStrButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Falcon.FalconMainApp.class).getContext().getResourceMap(devTestStrBox.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        testStrDescLabel.setText(resourceMap.getString("testStrDescLabel.text")); // NOI18N
        testStrDescLabel.setName("testStrDescLabel"); // NOI18N

        testStrText.setText(resourceMap.getString("testStrText.text")); // NOI18N
        testStrText.setName("testStrText"); // NOI18N

        testStrLabel.setText(resourceMap.getString("testStrLabel.text")); // NOI18N
        testStrLabel.setName("testStrLabel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(Falcon.FalconMainApp.class).getContext().getActionMap(devTestStrBox.class, this);
        sendTestStrButton.setAction(actionMap.get("sendTestStr")); // NOI18N
        sendTestStrButton.setText(resourceMap.getString("sendTestStrButton.text")); // NOI18N
        sendTestStrButton.setName("sendTestStrButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testStrDescLabel, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(testStrLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testStrText, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                    .addComponent(sendTestStrButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testStrLabel)
                    .addComponent(testStrText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testStrDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendTestStrButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void sendTestStr() {
        PacketExchange.getInstance().spoofIncomingPacket("........KB0MGQ",testStrText.getText());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton sendTestStrButton;
    private javax.swing.JLabel testStrDescLabel;
    private javax.swing.JLabel testStrLabel;
    private javax.swing.JTextField testStrText;
    // End of variables declaration//GEN-END:variables

}
